import { NextRequest, NextResponse } from "next/server";
import { buildEvidence, verifyCitations } from "@/lib/reasoning";
import { generateNarrative } from "@/lib/llm";
import { parseQuery, retrieveData } from "@/lib/aiPipeline";
import { weekOverWeek, monthOverMonth } from "@/lib/periods";
import { money } from "@/lib/currency";

export const dynamic = "force-dynamic";

// Reports run the same contract as the chat pipeline: retrieve live Meta data
// FIRST, then write from it. The prose is generated by the model against the
// evidence pack and every figure is citation-checked, rather than assembled
// from fixed sentence templates — which is what made reports read identically
// for every campaign regardless of what the data said.

const REPORT_SYSTEM = `You are a senior performance marketing analyst writing a client-ready campaign report.

Return STRICT JSON, no markdown fences, in this shape:
{"sections":[{"title":"...","body":"..."}],"priorities":[{"stars":5,"text":"..."}]}

Sections to produce, in order:
  Executive Summary · Performance Overview · Budget & Pacing · Creative Analysis ·
  Audience Analysis · Risks · Opportunities · Recommended Actions

Rules that matter more than style:
- Use ONLY figures present in the evidence JSON. Never derive, extrapolate or round into a new number.
- Currency is given in reporting.currency — use that symbol, never a dollar sign by default.
- If the evidence lacks something (no ad set data, no revenue tracking, too little history), SAY SO plainly in that section rather than filling the space.
- Vary the writing to the actual data. A healthy campaign and a failing one must not read the same.
- No filler, no restating the brief, no "in conclusion". 2–4 sentences per section.
- priorities: 2–4 items, stars 1–5, each naming a specific object and the action.

Write like a person who will be asked to defend every sentence.`;

export async function POST(req: NextRequest) {
  const { campaignId, compare } = await req.json();

  // ── Retrieve before writing ──────────────────────────────────────
  const retrieval = await retrieveData(
    String(campaignId),
    parseQuery("full performance report", []),
    new URL(req.url).origin,
  );
  if (!retrieval.ok) {
    return NextResponse.json(
      { error: "retrieval-failed", detail: retrieval.error ?? "Could not retrieve data from the Meta Ads API." },
      { status: 502 },
    );
  }

  const ev = await buildEvidence(campaignId);
  if (!ev) return NextResponse.json({ error: "Campaign not found" }, { status: 404 });

  const c = ev.campaign;
  const currency = ev.reporting.currency;

  // Period comparisons travel with the evidence so the model can speak to
  // movement, and so "not enough history" is stated rather than glossed over.
  const series = await import("@/lib/datasource").then((m) => m.dataSource.getDailySeries(campaignId));
  const wow = weekOverWeek(series);
  const mom = monthOverMonth(series);

  const payload = {
    evidence: ev,
    periods: { wow, mom },
    comparisonRequested: Boolean(compare),
    campaignStatus: retrieval.campaign?.status ?? null,
    pacing: retrieval.campaign?.pacingDetail ?? null,
    adsetPacing: (retrieval.adsets ?? []).map((a) => ({
      name: a.name, status: a.status ?? null, pacing: a.pacingDetail ?? null,
    })),
    dataFreshness: {
      source: retrieval.isLive ? "Meta Ads API (live)" : "seeded dataset",
      syncedAt: retrieval.syncedAt,
      refreshedForThisReport: retrieval.refreshed,
    },
  };

  const llm = await generateNarrative(
    REPORT_SYSTEM,
    `Evidence for ${c.name}:\n${JSON.stringify(payload)}\n\nWrite the report.`,
  );

  if (!llm.ok) {
    // No invented prose. The measured figures are still returned so the page
    // can show a factual summary clearly labelled as data, not analysis.
    return NextResponse.json({
      error: llm.reason === "no-api-key" ? "no-model-configured" : "model-unreachable",
      narrativeAvailable: false,
      detail: llm.detail,
      facts: factSheet(ev, wow, mom, currency),
      snapshot: ev.snapshot, campaign: c, currency,
      retrieval: { live: retrieval.isLive, refreshed: retrieval.refreshed, syncedAt: retrieval.syncedAt },
    }, { status: 200 });
  }

  let parsed: { sections?: { title: string; body: string }[]; priorities?: { stars: number; text: string }[] } | null = null;
  try {
    parsed = JSON.parse(llm.text.replace(/^```(?:json)?\s*|\s*```$/g, "").trim());
  } catch {
    parsed = null;
  }

  if (!parsed?.sections?.length) {
    return NextResponse.json({
      error: "unparseable-narrative",
      narrativeAvailable: false,
      facts: factSheet(ev, wow, mom, currency),
      snapshot: ev.snapshot, campaign: c, currency,
    }, { status: 200 });
  }

  // Every figure across every section must trace to the evidence.
  const joined = parsed.sections.map((s) => s.body).join("\n") +
    "\n" + (parsed.priorities ?? []).map((p) => p.text).join("\n");
  const check = verifyCitations(joined, ev);

  return NextResponse.json({
    narrativeAvailable: true,
    sections: parsed.sections,
    priorities: parsed.priorities ?? [],
    verified: check.ok,
    unverified: check.ok ? undefined : check.unverified.concat(check.misattributed),
    facts: factSheet(ev, wow, mom, currency),
    snapshot: ev.snapshot,
    campaign: c,
    currency,
    provider: llm.provider,
    model: llm.model,
    compareRows: compare ? comparisonRows(wow) : [],
    retrieval: { live: retrieval.isLive, refreshed: retrieval.refreshed, syncedAt: retrieval.syncedAt },
  });
}

/** Measured values, no interpretation. Always returned, so the page has real
 *  content even when the narrative model is unavailable. */
function factSheet(
  ev: Awaited<ReturnType<typeof buildEvidence>>,
  wow: ReturnType<typeof weekOverWeek>,
  mom: ReturnType<typeof monthOverMonth>,
  currency: string,
) {
  if (!ev) return [];
  const c = ev.campaign;
  const rows: { label: string; value: string }[] = [
    { label: "Spend", value: money(c.spend, currency) },
    { label: "Results", value: String(c.conv) },
    { label: "CTR", value: `${c.ctr}%` },
    { label: "CPC", value: money(c.cpc, currency) },
  ];
  if (ev.reporting.revenueTracked) {
    rows.push({ label: "Revenue", value: money(c.revenue, currency) });
    rows.push({ label: "ROAS", value: `${c.roas}x` });
  } else {
    rows.push({ label: "Revenue", value: "not reported by this account" });
  }
  rows.push({ label: "Ad sets", value: String(ev.adsets.length) });
  rows.push({
    label: "Week over week",
    value: wow.comparable
      ? wow.changes.filter((x) => x.changePct != null).map((x) => `${x.metric} ${x.changePct! > 0 ? "+" : ""}${x.changePct}%`).join(", ")
      : (wow.reason ?? "not comparable"),
  });
  rows.push({ label: "Month over month", value: mom.comparable ? "available" : (mom.reason ?? "not comparable") });
  return rows;
}

function comparisonRows(wow: ReturnType<typeof weekOverWeek>) {
  if (!wow.comparable) return [];
  return wow.changes
    .filter((c) => c.changePct != null)
    .map((c) => ({
      metric: c.metric,
      change: `${c.changePct! > 0 ? "+" : ""}${c.changePct}%`,
      better: c.better ?? false,
    }));
}
